# Generated by Django 5.1.6 on 2025-02-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_create_pgvector_extension'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documetns',
            table='document',
        ),
    ]
