# Generated by Django 5.1.6 on 2025-02-21 19:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0003_alter_documetns_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(verbose_name=1536)),
            ],
            options={
                'db_table': 'document_embedding',
            },
        ),
    ]
